from tools import tag, keyword, string, string_f, _for, _if, _else, _in, _not

console1 = [
	["<", tag("!DOCTYPE "), keyword("html"), ">"],
	["<", tag("html"), ">"],
	["<", tag("head"), ">"],
	["", "<", tag("title"), ">{% ", keyword("block "), "title %}{% ", keyword("endblock "), "%} - Flaskr</", tag("title"), ">"],
	["", "<", tag("link "), keyword("rel"), "=", string_f("\"stylesheet\" "), keyword("href"), "=", string("{{ url_for('static', filename='style.css') }}"), ">"],
	["</", tag("head"), ">"],
	[""],
	["</", tag("body"), ">"],
	["", "<", tag("h1"), ">Flaskr</", tag("h1"), ">"],
	["", "<", tag("ul"), "/>"],
	["", "", "{% ", _if, "g.user %}"],
	["", "", "", "<", tag("li"), "><", tag("span"), ">{{ g.user[", string("username"), "] }}</", tag("span"), "></", tag("li"), ">"],
	["", "", "", "<", tag("li"), "><", tag("a "), keyword("href"), "=", string("{{ url_for('auth.logout') }}"), ">Logout</", tag("a"), ">"],
	["", "", "{% ", _else, "%}"],
	["", "", "", "<", tag("li"), "><", tag("a "), keyword("href"), "=", string("{{ url_for('auth.register') }}"), ">Register</", tag("a"), ">"],
	["", "", "", "<", tag("li"), "><", tag("a "), keyword("href"), "=", string("{{ url_for('auth.login') }}"), ">Login</", tag("a"), ">"],
	["", "", "{% ", keyword("endif "), "%}"],
	["", "</", tag("ul"), ">"],
	["</", tag("nav"), ">"],
	["<", tag("section "), keyword("class"), "=", string("content"), ">"],
	["", "<", tag("header"), ">"],
	["", "", "{% ", keyword("block "), "header %}{% ", keyword("endblock")],
	["", "</", tag("header"), ">"],
	["", "{% ", _for, "message ", _in, "get_flashed_messages() %}"],
	["", "", "<", tag("div "), keyword("class"), "=", string("flash"), ">{{ message }}</", tag("div"), ">"],
	["", "{% ", keyword("endfor "), "%}"],
	["", "{% ", keyword("block "), "content %}{%", keyword("endblock"), "%}"],
	["</", tag("body"), ">"],	
	["</", tag("html"), ">"]
]

def template(name):
	console = [
		["{% ", keyword("extends "), "base.html ", "%}"],
		[""],
		["{% ", keyword("block "), "header %}"],
		["", "<", tag("h1"), ">{% ", keyword("block "), "title %}" + name + "{% ", keyword("endblock "), "%}"],
		["{% ", keyword("endblock "), "%}"],
		[""],
		["{% ", keyword("block "), "content %}"],
		["", "<", tag("form "), keyword("method"), "=", string("post"), ">"],
		["", "", "<", tag("label "), keyword("for"), "=", string("username"), ">Username</", tag("label"), ">"],
		["", "", "<", tag("input "), keyword("name"), "=", string_f("\"username\" "), keyword("id"), "=", string_f("\"username\" "), keyword("required"), ">"],
		["", "", "<", tag("label "), keyword("for"), "=", string("password"), ">Password</", tag("label"), ">"],
		["", "", "<", tag("input "), keyword("type"), "=", string("password"), keyword("name"), "=", string_f("\"password\" "), keyword("id"), "=", string_f("\"password\" "), keyword("required"), ">"],
		["", "", "<", tag("input "), keyword("type"), "=", string("submit"), keyword("value"), "=", string(name), ">"],
		["", "</", tag("form"), ">"],
		["{% ", keyword("endblock "), "%}"],
	]
	
	return console

console2 = [
	["{% ", keyword("extends "), "base.html ", "%}"],
	[""],
	["{% ", keyword("block "), "header %}"],
		["", "<", tag("h1"), ">{% ", keyword("block "), "title %}Posts{% ", keyword("endblock "), "%}"],
	["", "{% ", _if, "g.user %}"],
	["", "", "<", tag("a "), keyword("class"), "=", string_f("\"actiob\" "), keyword("href"), "=", string("{{ url_for('blog.create') }}"), ">New</", tag("a"), ">"],
	["", "{% ", keyword("endif "), "%}"],
	["{% ", keyword("endblock "), "%}"],
	[""],
	["{% ", keyword("block "), "content %}"],
	["", "{% ", _for, "block", _in, "posts %}"],
	["", "", "<", tag("article "), keyword("class"), "=", string("post"), ">"],
	["", "", "", "<", tag("header"), ">"],
	["", "", "", "", "<", tag("div"), ">"],
	["", "", "", "", "", "<", tag("h1"), ">{{ post[", string("title"), "] }}</", tag("h1"), ">"],
	["", "", "", "", "", "<", tag("div "), keyword("class"), "=", string("about"), ">by {{ post[", string("username"), "] }} on {{ post[", string("created"), "].strftime(", string("%Y-%m-%d"), ") }}</", tag("div"), ">"],
	["", "", "", "", "</", tag("div"), ">"],
	["", "", "", "", "{% ", _if, "g.user[", string("id"), "] == post[", string("author_id"), "] %}"],
	["", "", "", "", "", "<", tag("a "), keyword("class"), "=", string_f("\"action\" "), keyword("href"), "=", string("{{ url_for('blog.update', id=post['id']) }}"), ">Edit</", tag("a"), ">"],
	["", "", "", "", "</", tag("header"), ">"],
	["", "", "", "", "<", tag("p "), keyword("class"), "=", string("body"), ">{{ post[", string("body"), " }}</", tag("p"), ">"],
	["", "", "", "</", tag("article"), ">"],
	["", "", "{% ", _if, _not, "loop.last", "%}"],
	["", "", "", "<", tag("hr"), ">"],
	["", "", "{% ", keyword("endif "), "%}"],
	["", "{% ", keyword("endfor "), "%}"],
	["{% ", keyword("endblock "), "%}"],
]

console3 = [
	["{% ", keyword("extends "), "base.html ", "%}"],
	[""],
	["{% ", keyword("block "), "header %}"],
	["", "<", tag("h1"), ">{% ", keyword("block "), "title %}New Post{% ", keyword("endblock "), "%}"],
	["{% ", keyword("endblock "), "%}"],
	[""],
	["{% ", keyword("block "), "content %}"],
	["", "<", tag("form "), keyword("method"), "=", string("post"), ">"],
	["", "", "<", tag("label "), keyword("for"), "=", string("title"), ">Title</", tag("label"), ">"],
	["", "", "<", tag("input "), keyword("name"), "=", string_f("\"title\" "), keyword("id"), "=", string_f("\"title\" "), keyword("value"), "=", string_f("\"{{ request.form[\"title\"] }}\" "), keyword("required"), ">"],
	["", "", "<", tag("label "), keyword("for"), "=", string("body"), ">Body</", tag("label"), ">"],
	["", "", "<", tag("textarea "), keyword("name"), "=", string_f("\"body\" "), keyword("id"), "=", string("body"), ">{{ request.form[", string("body"), "] }}</", tag("textarea"), ">"],
	["", "", "<", tag("input "), keyword("type"), "=", string("submit"), keyword("value"), "=", string("Save"), ">"],
	["", "</", tag("form"), ">"],
	["{% ", keyword("endblock "), "%}"],
]

content = [
	"Pagina base",
	console1,
	"Pagina register",
	template("Register"),
	"Pagina login",
	template("Login"),
	"Pagina blog",
	console2,
	"Pagina creare blog",
	console3
]
